CREATE TABLE User(
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL
);

CREATE TABLE Note(
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(100) NOT NULL,
  Content TEXT(50000) NOT NULL,
  UserId INT NOT NULL,
  DateModified DATETIME NOT NULL,
  FOREIGN KEY (UserId) REFERENCES User(Id)
);

SELECT * from Note;